---
- name: Install required utilities / dependencies
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes
