---
- name: Install required utilities / dependencies
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

# - name: Add Docker’s official GPG key
#   shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    # id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

# - name: set up the stable repository
#   shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Add Docker stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes
